allowBuilds:
  esbuild: set this to true or false
  msw: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
minimumReleaseAgeExclude:
  - mix-n-matchers@2.3.0
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
