/** RFC 9457: Problem Details for HTTP APIs */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type. */
  type?: string;
  /** A short, human-readable summary of the problem type. */
  title?: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  status?: number;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
}

/** A more flexible version of ProblemDetails that allows additional properties. */
export interface LooseProblemDetails extends ProblemDetails {
  [key: string]: unknown;
}

export class ProblemResponse extends Response {
  static problem(
    problem: LooseProblemDetails,
    init?: Omit<ResponseInit, "status">,
  ): ProblemResponse {
    const { status = 500 } = problem;
    const headers = new Headers(init?.headers);
    headers.set("Content-Type", "application/problem+json");
    return Object.setPrototypeOf(
      Response.json(problem, {
        ...init,
        status,
        headers,
      }),
      ProblemResponse.prototype,
    );
  }
}
