import type { StandardSchemaV1 } from "@standard-schema/spec";
import type { ProblemResponse } from "./index.ts";

// oxlint-disable-next-line typescript/no-redundant-type-constituents
export type Compute<T> = { [K in keyof T]: T[K] } & unknown;
export type PickPartial<T, K extends keyof T> = Compute<Partial<Pick<T, K>> & Omit<T, K>>;

export type NonReducibleUnknown = {} | null | undefined;
export namespace LooseAutocomplete {
  export type Unknown<T> = T | NonReducibleUnknown;
  export type String<T extends string> = T | (string & {});
}

/** RFC 9457: Problem Details for HTTP APIs */
export interface ProblemDetails<TType extends string = string> {
  /** A URI reference that identifies the problem type. */
  type?: TType;
  /** A short, human-readable summary of the problem type. */
  title?: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  status?: number;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
}

/** A more flexible version of ProblemDetails that allows additional properties. */
export interface LooseProblemDetails<TType extends string = string> extends ProblemDetails<TType> {
  [key: string]: unknown;
}

// status is determined by the problem, so it should not be included in the init object
type StatuslessResponseInit = Omit<ResponseInit, "status"> & { status?: undefined };

export type ProblemSchema<TType extends string = string> = StandardSchemaV1<
  ProblemDetails<TType>,
  LooseProblemDetails<TType>
>;

export type ProblemConstructResult<TType extends string, TSchema extends ProblemSchema<TType>> =
  | PickPartial<StandardSchemaV1.InferInput<TSchema>, "type">
  | [
      problem: PickPartial<StandardSchemaV1.InferInput<TSchema>, "type">,
      init?: StatuslessResponseInit,
    ];

export interface ProblemFactory<
  TType extends string = string,
  TSchema extends ProblemSchema = ProblemSchema,
  TArgs extends any[] = any[],
> {
  (...args: TArgs): ProblemResponse;
  parse: (
    value: LooseAutocomplete.Unknown<StandardSchemaV1.InferInput<TSchema>>,
  ) => StandardSchemaV1.InferOutput<TSchema>;
  safeParse: (
    value: LooseAutocomplete.Unknown<StandardSchemaV1.InferInput<TSchema>>,
  ) => StandardSchemaV1.Result<StandardSchemaV1.InferOutput<TSchema>>;
  type: TType;
  schema: TSchema;
}
