import type { StandardSchemaV1 } from "@standard-schema/spec";
import type { ProblemResponse } from "./index.ts";

export type NonReducibleUnknown = {} | null | undefined;
export namespace LooseAutocomplete {
  export type Unknown<T> = T | NonReducibleUnknown;
  export type String<T extends string> = T | (string & {});
}

/** RFC 9457: Problem Details for HTTP APIs */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type. */
  type?: string;
  /** A short, human-readable summary of the problem type. */
  title?: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  status?: number;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
}

/** A more flexible version of ProblemDetails that allows additional properties. */
export interface LooseProblemDetails extends ProblemDetails {
  [key: string]: unknown;
}

// status is determined by the problem, so it should not be included in the init object
type StatuslessResponseInit = Omit<ResponseInit, "status"> & { status?: undefined };

export type ProblemSchema = StandardSchemaV1<ProblemDetails, LooseProblemDetails>;

export type ProblemConstructResult<TSchema extends ProblemSchema> =
  | StandardSchemaV1.InferInput<TSchema>
  | [problem: StandardSchemaV1.InferInput<TSchema>, init?: StatuslessResponseInit];

export interface ProblemFactory<
  TSchema extends ProblemSchema = ProblemSchema,
  TArgs extends any[] = any[],
> {
  (...args: TArgs): ProblemResponse;
  parse: (
    value: LooseAutocomplete.Unknown<StandardSchemaV1.InferInput<TSchema>>,
  ) => StandardSchemaV1.InferOutput<TSchema>;
  safeParse: (
    value: LooseAutocomplete.Unknown<StandardSchemaV1.InferInput<TSchema>>,
  ) => StandardSchemaV1.Result<StandardSchemaV1.InferOutput<TSchema>>;
}
