import type { StandardSchemaV1 } from "@standard-schema/spec";

import type { ProblemResponse } from "../../index.ts";
import type { PickPartial } from "./utils.ts";

/** RFC 9457: Problem Details for HTTP APIs */
export interface ProblemDetails<TType extends string = string> {
  /** A URI reference that identifies the problem type. */
  type?: TType;
  /** A short, human-readable summary of the problem type. */
  title?: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  status?: number;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
}

/** A more flexible version of ProblemDetails that allows additional properties. */
export interface LooseProblemDetails<TType extends string = string> extends ProblemDetails<TType> {
  [key: string]: unknown;
}

// status is determined by the problem, so it should not be included in the init object
type StatuslessResponseInit = Omit<ResponseInit, "status"> & { status?: undefined };

export type ProblemSchema<TType extends string = string> = StandardSchemaV1<
  ProblemDetails<TType>,
  LooseProblemDetails<TType>
>;

export type ProblemConstructResult<TType extends string, TSchema extends ProblemSchema<TType>> =
  | PickPartial<StandardSchemaV1.InferInput<TSchema>, "type">
  | [
      problem: PickPartial<StandardSchemaV1.InferInput<TSchema>, "type">,
      init?: StatuslessResponseInit,
    ];

export interface ProblemDefinition<
  TType extends string = string,
  TSchema extends ProblemSchema<TType> = ProblemSchema<TType>,
> {
  type: TType;
  schema: TSchema;
}

export interface ProblemFactory<
  TType extends string = string,
  TSchema extends ProblemSchema<TType> = ProblemSchema<TType>,
  TArgs extends Array<any> = Array<any>,
> extends ProblemDefinition<TType, TSchema> {
  (...args: TArgs): ProblemResponse;
}
